---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Semaphore service is runnning
      ansible.builtin.uri:
        url: http://localhost:3000
        return_content: true
      register: this
      failed_when: "'<title>Ansible Semaphore</title>' not in this.content"
